PACKAGE_NAME="linuwu-sense"
PACKAGE_VERSION="1.2.anv16s41"

BUILT_MODULE_NAME[0]="linuwu_sense"
BUILT_MODULE_LOCATION[0]="src"
DEST_MODULE_LOCATION[0]="/kernel/drivers/platform/x86"

MAKE[0]="make KVER=${kernelver} all"
CLEAN="make KVER=${kernelver} clean"

AUTOINSTALL="yes"
